services:
  app:
    build: .
    ports:
      - "5555:5173"
    volumes:
      - ./src:/app/src
      - ./index.html:/app/index.html
      - ./public:/app/public
    depends_on:
      - texlive
    environment:
      - TEXLIVE_URL=http://texlive:5001/

  texlive:
    build: ./texlive-server
    ports:
      - "5001:5001"
